[package]
name = "fastfetch-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
libfastfetch = { path = "../libfastfetch" }
anyhow = "1.0"
rayon = "1.10"
clap = { version = "4.5", features = ["derive"] }
