[workspace]
members = [
  "fastfetch-cli", "libfastfetch",
]
resolver = "3"

[package]
name = "fastfetch-rs"
version = "0.0.1"
edition = "2024"
license = "MIT"
description = "fastfetch, but written in rust"
repository = "https://github.com/ezozbek36/fastfetch-rs"
authors = ["Ezozbek Rasulov <contact@ezozbek.dev>"]
# TODO: publish after initial release
publish = false

[profile.release]
strip = true
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
