[package]
name = "libfastfetch"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
publish.workspace = true

[dependencies]
anyhow = "1.0"
rayon = "1.10"

[target.'cfg(unix)'.dependencies]
libc = "0.2"
