name: Test CI

on: [push, pull_request]

jobs:
  test-flake:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Check up flake configuration
        run: nix flake check --all-systems --show-trace

  test-project:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Run cargo check on all workspace members
        run: nix develop --command cargo check --workspace

      - name: Run cargo fmt check
        run: nix develop --command cargo fmt --check

      - name: Run cargo clippy on all workspace members
        run: nix develop --command cargo clippy --workspace --all-targets -- -D warnings

      - name: Run cargo tests on all workspace members
        run: nix develop --command cargo test --workspace

      - name: Build project with Nix
        run: nix build

      - name: Verify binary functionality
        run: |
          ./result/bin/fastfetch-rs --version
          ./result/bin/fastfetch-rs --help
          ./result/bin/fastfetch-rs --list-modules
